server:
  port: 8090
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ###
            client-secret: ###
            scope: openid, email, profile, https://www.googleapis.com/auth/calendar
          facebook:
            client-id: ###
            client-secret: ###
            scope: user_posts





